apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: "0.7.2"
    chart: immich
    helm:
      values: |
        immich:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: "v1.134.0"

          # Set replica count to 1 for Immich server
          server:
            replicaCount: 1

          # Environment variables to override service discovery
          env:
            REDIS_HOSTNAME: "immich-redis-master"
            DB_HOSTNAME: "immich-postgresql"
            DB_DATABASE_NAME: "immich"
            DB_USERNAME: "immich"
            # Remove DB_PASSWORD since we'll use existingSecret

          persistence:
            library:
              enabled: true
              type: pvc
              existingClaim: "immich-server-library"
              accessMode: ReadWriteOnce
              size: 100Gi
            
            uploads:
              enabled: true
              type: pvc
              existingClaim: "immich-server-uploads"
              accessMode: ReadWriteOnce
              size: 50Gi

          postgresql:
            enabled: true
            nameOverride: "postgresql"
            fullnameOverride: "immich-postgresql"
            auth:
              username: immich
              database: immich
            primary:
              persistence:
                enabled: true
                size: 20Gi
            # Ensure service is created
            service:
              ports:
                postgresql: 5432

          redis:
            enabled: true
            nameOverride: "redis"  
            fullnameOverride: "immich-redis"
            auth:
              enabled: false
            architecture: standalone
            master:
              persistence:
                enabled: true
                size: 8Gi
            # Ensure service is created  
            service:
              ports:
                redis: 6379

          ingress:
            main:
              enabled: true
              hosts:
                - host: immich.local
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
