apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Default to production without monitoring (safer)
resources:
  - overlays/production-no-monitoring

# You can change this to other environments:
# resources:
#   - overlays/production          # (with monitoring if CRDs available)
#   - overlays/development
#   - overlays/monitoring
#   - base