apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Default to production overlay
resources:
  - overlays/production

# You can change this to development for dev deployments:
# resources:
#   - overlays/development

# Or use base directly:
# resources:
#   - base