# Values for the Immich Helm chart dependency
immich:
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: "v1.134.0" # Check for the latest stable version

  postgresql:
    enabled: true
    auth:
      username: immich
      database: immich

  redis:
    enabled: true

  ingress:
    main:
      enabled: true
      hosts:
        - host: immich.local
          paths:
            - path: /
              pathType: ImplementationSpecific