# Values for the Immich Helm chart dependency
# Note: These values are passed to the immich subchart
immich:
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: "v1.134.0" # Check for the latest stable version

  # Persistence configuration for Immich
  persistence:
    library:
      enabled: true
      type: pvc
      existingClaim: "immich-server-library"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 100Gi
    
    uploads:
      enabled: true
      type: pvc
      existingClaim: "immich-server-uploads"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 50Gi

  # Disable built-in PostgreSQL and Redis, use external services
  postgresql:
    enabled: false

  redis:
    enabled: false

  # Configuration for external PostgreSQL
  env:
    DB_HOSTNAME: "immich-postgresql"
    DB_PORT: "5432"
    DB_USERNAME: "immich"
    DB_DATABASE_NAME: "immich"
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: "immich-postgresql-temp"
          key: "password"
    
    # Configuration for external Redis
    REDIS_HOSTNAME: "immich-redis-master"
    REDIS_PORT: "6379"

  ingress:
    main:
      enabled: true
      hosts:
        - host: immich.local
          paths:
            - path: /
              pathType: ImplementationSpecific