# Values for the Immich Helm chart dependency
# Note: These values are passed to the immich subchart
immich:
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: "v1.134.0" # Check for the latest stable version

  # Persistence configuration for Immich
  persistence:
    library:
      enabled: false
    
    # Additional persistence volumes that might be needed
    uploads:
      enabled: false

  postgresql:
    enabled: true
    auth:
      username: immich
      database: immich
      # You might want to set a password or use existing secret
      # password: "your-password"
      # existingSecret: "immich-postgres-secret"
    primary:
      persistence:
        enabled: true
        size: 20Gi

  redis:
    enabled: true
    auth:
      enabled: false # Set to true for production
    master:
      persistence:
        enabled: true
        size: 8Gi

  ingress:
    main:
      enabled: true
      hosts:
        - host: immich.local
          paths:
            - path: /
              pathType: ImplementationSpecific