---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-postgresql
  namespace: default
spec:
  encryptedData:
    password: AgC7anuc/PqelAr+xRUo3fhx6wrFOV/hTHnuqVasO8rXtnPfHeCiuxkjShMKSSZjU0Le7oTjs6LNlpu/JK1OSrDTBC1DEX2vdbPMVuP/WMk4oI/9Wu8AK9zC3yg+zIrPs2hqyAONOoSaL7RSNrwjeE7njXmMpVPuWI+6/2u9mZJcz0rcZRlRpfcirZgmMrvndJJ0ZVyS7qVX45mrZU/o17AfHS8S7tZd5eJFlsuLQexpJMcT9FXbnKrsNbTrXG6RTQbxxUK3N+Oancoo5kysndez4SqagewPubOM3KwX4L2mbRtHKhOUXKWexLKDnWJgE13yz25oLAjzzPHiKa59MMGL/buCYYghHzxlCJP+PorOBruC0oXLZOefBhonCPBmjimRbp31G4y86AF/C5jHMUB/7V3P4Vl1d3tQMkhIYE8O7+b0jNTcfQH1THdPc3mbVUUvqrR2MYRpyRZm6xvwhAMHN90aOXV1JAXK83RR8z2xjvibClYm5DlhCub3iHT0itJ3PCpyHZOI0xK2Dq+sPYaDtzfbLDRXSZwwdhrXq73DBwiiQyvCeQQFp1n4yVedoP2T9i2j9y6eYYGk9KAXkhutwSzmymIWnn7hccXojth09AEyioku9nfW7GJVVypS55aep0UzTRhqusyC22ZaOtM/4iDGCzS6ZBfuTa+s4H3xmc+SWh46OIBMx0vQW8GrCkOWCGRnlqeCwa63ft/hyrYi
  template:
    metadata:
      creationTimestamp: null
      name: immich-postgresql
      namespace: default
    type: Opaque
