apiVersion: v1
kind: Service
metadata:
  name: immich-server-metrics
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3001"
    prometheus.io/path: "/api/server-info/stats"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: immich-server
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: monitoring
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/component: server-metrics
  endpoints:
    - port: metrics
      path: /api/server-info/stats
      interval: 30s
      scrapeTimeout: 10s
---
# PostgreSQL Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: immich-postgresql-exporter
  namespace: immich
  labels:
    app.kubernetes.io/name: postgresql-exporter
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
  selector:
    app: immich-postgresql-pgvector
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: immich-postgresql
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: monitoring
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql-exporter
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
