apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-app-of-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/immich-sealed  # Update with your repo URL
    targetRevision: HEAD
    path: argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
