apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-production
  namespace: argocd
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: production
spec:
  project: immich
  source:
    repoURL: https://github.com/hazyView/immich-sealed  # Update with your repo URL
    targetRevision: HEAD
    path: overlays/production
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
