apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-redis
  namespace: argocd
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: redis
spec:
  project: immich
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "19.6.4"
    chart: redis
    helm:
      values: |
        auth:
          enabled: false
        architecture: standalone
        master:
          persistence:
            enabled: true
            size: 8Gi
        # Override service name for consistency
        fullnameOverride: "immich-redis"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
