apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-development
  namespace: argocd
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: development
spec:
  project: immich
  source:
    repoURL: https://github.com/your-org/immich-sealed  # Update with your repo URL
    targetRevision: HEAD
    path: overlays/development
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
