apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-kustomize
  namespace: argocd
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: kustomize-deployment
spec:
  project: immich
  source:
    repoURL: https://github.com/hazyView/immich-sealed  # Update with your repo URL
    targetRevision: HEAD
    path: overlays/production-no-monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: immich-server
    jsonPointers:
    - /spec/replicas
