apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: immich
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        return 301 https://$server_name$request_uri;
    }
    
    server {
        listen 443 ssl;
        server_name _;
        
        ssl_certificate /etc/ssl/certs/tls.crt;
        ssl_certificate_key /etc/ssl/private/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        
        client_max_body_size 50G;
        
        location / {
            proxy_pass http://immich-server:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 600s;
            proxy_send_timeout 600s;
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: immich-tls
  namespace: immich
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lKQU1mOGtOZGtOR3FIRENRUEFEQURBUEF3SERFRE1Ba0dBMVVFQmhNQ1VWTXgKRERBS0JnTlZCQWdNQTFOVUlERE1Ba0dBMVVFQndsQ1FWTkRRVEJKQmdOVkJBb01RazVCVFVWRE1Ca0dBMVVFQ3d3UQpEQkZ3Y21WclpYTUdBMVVFQXd3TGFXMXRhV05vTG14dlkyRnNNQjRYRFRJek1EQXhNREE1TVRFMU0xb1hEVEl6Ck1ERXhNREE5TVRFMU0xb3dOVEVMTUFrR0ExVUVCaE1DVmxNeEREQUtCZ05WQkFnTUExTlVMREFwQmdOVkJBb00KQWs1QlRVVkpNQWtHQTFVRUNBd0JjSEpsYTJWelFEQWdCZ05WQkFNTUNXbHRiV2xqYURNeEREQUtCZ05WQkFzTQpBRGd3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzlHMmlzQWdKUW5mQzhZUWNYCkduWE5sdWcvVXhrSlRjeDFCSjJKSDRLdCtoNlhCU3ZrcUNPRmZpc3VRN0xCK3FQYlpWUzN5YXpmZjRncitCcEcKMGtHcXZQUk9MQVV5TVpkTFY4OFE1M2c4blZCdnIvLy8zT0lON21VYWNtRkhsMHhtSDZMdS9rdEVzU3NDOVUrUwpwaE5Qa3lNbGFrWmpaTXZCLzlhOGQ5V3M4VHNzWEpKb1R5VTlwYWZsRWY4TFhOZS9GRlFLUDZkK1JQVjArbVNQCkZJaGdHNUlEOFJIMGdmUjYzYnVZQU9hTE1hbWVRSVBFUTBBM1FKbm9CcWF6cU5OSDd5bXllSnQ3SlZJVFR0UTYKWDBVMzJpUGtWYlJOM0Y0V3JEQ2x4TDhWYjlPQ3NJdE92NDlrM1VxcytqWkUrSFhRdGh4b3pMck1tVGlJNFA5YgpBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCUTJScUV4WFlOajJyK0NiTHBGSGtzSXlydDNLSDlTCmNPZnVQNFJDQzVZNG1MNmdWOFlXcGhiVExYV0dCZ3dHVCtYUVBndldaN1gvQStoTzJLTndLNUJLSkozUldvZUUKZXdlRjQxTnZFdkxJUVBqSjZ1ZGRvTkh0cnN3cFN1VkhOOVl1cVk3L0Y2Q0dGNzNSRUhDME5teGw4Y1p3cG5FWgo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzlHMmlzQWdKUW5mQzgKWVFjWEduWE5sdWcvVXhrSlRjeDFCSjJKSDRLdCtoNlhCU3ZrcUNPRmZpc3VRN0xCK3FQYlpWUzN5YXpmZjRncgorQnBHMGtHcXZQUk9MQVV5TVpkTFY4OFE1M2c4blZCdnIvLy8zT0lON21VYWNtRkhsMHhtSDZMdS9rdEVzU3NDCjlVK1NwaE5Qa3lNbGFrWmpaTXZCLzlhOGQ5V3M4VHNzWEpKb1R5VTlwYWZsRWY4TFhOZS9GRlFLUDZkK1JQWDAKK21TUEZJaGdHNUlEOFJIMGdmUjYzYnVZQU9hTE1hbWVRSVBFUTBBM1FKbm9CcWF6cU5OSDd5bXllSnQ3SlZJVApUdFE2WDBVMzJpUGtWYlJOM0Y0V3JEQ2x4TDhWYjlPQ3NJdE92NDlrM1VxcytqWkUrSFhRdGh4b3pMck1tVGlJCjRQOWJBZ01CQUFFQ2dnRUFJU1NzSDBJQ3lEN2grVkY0UHA0c3dGYXNZa3BNOUJBNG81MUwvVFY=
