---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-server-library
  namespace: immich
  labels:
    app: immich
    component: library-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # Uncomment and specify storageClassName if you have a specific storage class
  # storageClassName: "your-storage-class-name"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-server-uploads
  namespace: immich
  labels:
    app: immich
    component: uploads-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # Uncomment and specify storageClassName if you have a specific storage class
  # storageClassName: "your-storage-class-name"
