apiVersion: v1
kind: Service
metadata:
  name: immich-server-nodeport
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001  # This will be accessible on all cluster nodes
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
