apiVersion: v1
kind: Service
metadata:
  name: immich-server-loadbalancer
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
