apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich
        app.kubernetes.io/component: server
    spec:
      initContainers:
      - name: init-upload-dirs
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Creating required upload directories..."
          mkdir -p /upload/library
          mkdir -p /upload/upload
          mkdir -p /upload/profile
          mkdir -p /upload/thumbs
          mkdir -p /upload/encoded-video
          mkdir -p /upload/backups
          
          # Create .immich files for folder verification
          touch /upload/library/.immich
          touch /upload/upload/.immich
          touch /upload/profile/.immich
          touch /upload/thumbs/.immich
          touch /upload/encoded-video/.immich
          touch /upload/backups/.immich
          
          echo "Upload directories initialized successfully"
          ls -la /upload/
        volumeMounts:
        - name: uploads-storage
          mountPath: /upload
      containers:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:v1.135.0
        ports:
        - containerPort: 2283
          name: http
        env:
        - name: REDIS_HOSTNAME
          value: "immich-redis-master"
        - name: DB_HOSTNAME
          value: "immich-postgresql-pgvector"
        - name: DB_DATABASE_NAME
          value: "immich"
        - name: DB_USERNAME
          value: "immich"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "immich-postgresql-temp"
              key: "password"
        - name: DB_VECTOR_EXTENSION
          value: "pgvector"
        - name: IMMICH_VERSION
          valueFrom:
            configMapKeyRef:
              name: immich-config
              key: IMMICH_VERSION
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: immich-config
              key: LOG_LEVEL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: immich-config
              key: NODE_ENV
        volumeMounts:
        - name: uploads-storage
          mountPath: /usr/src/app/upload
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 2283
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 2283
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: immich-server-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 2283
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: server
